// ==UserScript==
// @name         Cover Next (Bearbit)
// @namespace    http://tampermonkey.net/
// @version      2.00
// @description  tools that will help you see new items and make it easier for you to use the website to load bittorrent.
// @author       NEKO
// @icon         https://i.imgur.com/qTvfJSr.png
// @match        https://www.bearbit.co
// @match        https://www.bearbit.co/index.php*
// @match        https://www.bearbit.co/viewno18.php*
// @match        https://www.bearbit.co/viewbr.php*
// @match        https://www.bearbit.co/viewno18sb.php*
// @match        https://www.bearbit.co/viewbrsb.php*
// @match        https://www.bearbit.co/torrent_day.php*
// @match        https://www.bearbit.co/torrent_week.php*
// @match        https://www.bearbit.co/torrent_month.php*
// @match        https://www.bearbit.co/upfinish.php*
// @match        https://www.bearbit.co/downfinish.php*
// @match        https://www.bearbit.co/details.php*
// @match        https://bearbit.co
// @match        https://bearbit.co/index.php*
// @match        https://bearbit.co/viewno18.php*
// @match        https://bearbit.co/viewbr.php*
// @match        https://bearbit.co/viewno18sb.php*
// @match        https://bearbit.co/viewbrsb.php*
// @match        https://bearbit.co/torrent_day.php*
// @match        https://bearbit.co/torrent_week.php*
// @match        https://bearbit.co/torrent_month.php*
// @match        https://bearbit.co/upfinish.php*
// @match        https://bearbit.co/downfinish.php*
// @match        https://bearbit.co/details.php*
// @grant        GM_addStyle
// @grant        GM_xmlhttpRequest
// @require      https://raw.githubusercontent.com/kon3ko/cover-next/master/dist/cover-next.js?version=2.00
// @updateURL    https://raw.githubusercontent.com/kon3ko/cover-next/master/cover-next.user.js
// @downloadURL  https://raw.githubusercontent.com/kon3ko/cover-next/master/cover-next.user.js
// @supportURL   https://github.com/kon3ko/cover-next/issues
// @connect      img.in.th
// @connect      bpicc.cc
// @connect      imgtrue.com
// @connect      imdb.com
// @connect      55xo.co
// @connect      imgur.com
// @connect      in.th
// @connect      postto.me
// @connect      javstore.net
// @connect      i-pic.info
// @connect      picstate.com
// @connect      bpicc.com
// @connect      roop.xyz
// @connect      mpic.ws
// @connect      img.live
// @connect      shotcan.com
// @connect      ibb.co
// @connect      lmgbb.me
// @connect      4shared.com
// @connect      lookimg.com
// @connect      gstatic.com
// @connect      wp.com
// @connect      steamstatic.com
// @connect      tokopedia.net
// @connect      4gamers.com.tw
// @connect      imgbb.me
// @connect      clip18zeed.com
// @connect      mx7.com
// @connect      youtube.com
// @connect      youtube.be
// @connect      8e88.in.th
// @connect      clipxxx.live
// @connect      i-pic.info
// @connect      thaibuzz.com
// @connect      imgmak.com
// @connect      imgbb.me
// @connect      picz.in.th
// @connect      234.in.th
// @connect      best-story.net
// @connect      uppic.cc
// @connect      uppicimg.com
// @connect      uppic.xyz
// @connect      gifyu.com
// @connect      imgvb.com
// @connect      up-pic.com
// @connect      pic.4th.in
// @connect      *
// ==/UserScript==
