// ==UserScript==
// @name         Cover Next (Siambit)
// @namespace    http://tampermonkey.net/
// @version      1.4.1
// @description  tools that will help you see new items and make it easier for you to use the website to load bittorrent.
// @author       NEKO
// @icon         https://i.imgur.com/qTvfJSr.png
// @match        https://www.siambit.me
// @match        https://www.siambit.me/index.php*
// @match        https://www.siambit.me/viewno18.php*
// @match        https://www.siambit.me/viewbr.php*
// @match        https://www.siambit.me/viewno18sb.php*
// @match        https://www.siambit.me/viewbrsb.php*
// @match        https://www.siambit.me/torrent_day.php*
// @match        https://www.siambit.me/torrent_week.php*
// @match        https://www.siambit.me/torrent_month.php*
// @match        https://www.siambit.me/upfinish.php*
// @match        https://www.siambit.me/downfinish.php*
// @match        https://www.siambit.me/details.php*
// @match        https://siambit.io
// @match        https://siambit.io/index.php*
// @match        https://siambit.io/viewno18.php*
// @match        https://siambit.io/viewbr.php*
// @match        https://siambit.io/viewno18sb.php*
// @match        https://siambit.io/viewbrsb.php*
// @match        https://siambit.io/torrent_day.php*
// @match        https://siambit.io/torrent_week.php*
// @match        https://siambit.io/torrent_month.php*
// @match        https://siambit.io/upfinish.php*
// @match        https://siambit.io/downfinish.php*
// @match        https://siambit.io/details.php*
// @match        https://thaibit.net
// @match        https://thaibit.net/index.php*
// @match        https://thaibit.net/viewno18.php*
// @match        https://thaibit.net/viewbr.php*
// @match        https://thaibit.net/viewno18sb.php*
// @match        https://thaibit.net/viewbrsb.php*
// @match        https://thaibit.net/torrent_day.php*
// @match        https://thaibit.net/torrent_week.php*
// @match        https://thaibit.net/torrent_month.php*
// @match        https://thaibit.net/upfinish.php*
// @match        https://thaibit.net/downfinish.php*
// @match        https://thaibit.net/details.php*
// @grant        GM_addStyle
// @grant        GM_xmlhttpRequest
// @require      https://raw.githubusercontent.com/nutpaker/cover-next/master/dist/cover-next.js?version=1.40
// @updateURL    https://raw.githubusercontent.com/nutpaker/cover-next/master/cover-next.user.js
// @downloadURL  https://raw.githubusercontent.com/nutpaker/cover-next/master/cover-next.user.js
// @supportURL   https://github.com/kon3ko/cover-next/issues
// @connect      img.in.th
// @connect      bpicc.cc
// @connect      imgtrue.com
// @connect      imdb.com
// @connect      55xo.co
// @connect      imgur.com
// @connect      in.th
// @connect      postto.me
// @connect      javstore.net
// @connect      i-pic.info
// @connect      picstate.com
// @connect      bpicc.com
// @connect      roop.xyz
// @connect      mpic.ws
// @connect      img.live
// @connect      shotcan.com
// @connect      ibb.co
// @connect      lmgbb.me
// @connect      4shared.com
// @connect      lookimg.com
// @connect      gstatic.com
// @connect      wp.com
// @connect      steamstatic.com
// @connect      tokopedia.net
// @connect      4gamers.com.tw
// @connect      imgbb.me
// @connect      clip18zeed.com
// @connect      mx7.com
// @connect      youtube.com
// @connect      youtube.be
// @connect      8e88.in.th
// @connect      clipxxx.live
// @connect      i-pic.info
// @connect      thaibuzz.com
// @connect      imgmak.com
// @connect      imgbb.me
// @connect      picz.in.th
// @connect      234.in.th
// @connect      best-story.net
// @connect      uppic.cc
// @connect      uppicimg.com
// @connect      uppic.xyz
// @connect      gifyu.com
// @connect      imgvb.com
// @connect      up-pic.com
// @connect      *
// ==/UserScript==
